export const flights = {
  f1: {
    id: "AIR101",
    aircraft: "Airbus A320",
    airline: "Air India",
    from: "Delhi (DEL)",
    to: "Mumbai (BOM)",
    departure: "2026-07-30T17:45:00",
    arrival: "2026-07-30T19:55:00",
    gate: "A4",
    terminal: "1",
    delay: 0,
    status: "BOARDING", // BOARDING | SCHEDULED | DEPARTED | DELAYED
    boardingStarted: true,

    layouts: ["A", "B", "C", "D", "E", "F"],

    seats: [
      [1, 1, 0, 1, 0, 1],
      [0, 1, 1, 1, 1, 1],
      [1, 0, 0, 0, 1, 1],
      [1, 1, 1, 1, 1, 1],
      [0, 0, 1, 1, 0, 1],
    ],
  },

  f2: {
    id: "AIR205",
    aircraft: "Boeing 737-800",
    airline: "IndiGo",
    from: "Bengaluru (BLR)",
    to: "Hyderabad (HYD)",
    departure: "2026-07-31T00:30:00",
    arrival: "2026-07-31T01:40:00",
    gate: "B2",
    terminal: "2",
    delay: 10,
    status: "BOARDING",
    boardingStarted: true,

    layouts: ["A", "B", "C", "D", "E", "F"],

    seats: [
      [1, 1, 1, 0, 1, 1],
      [1, 0, 1, 1, 1, 0],
      [1, 1, 0, 1, 0, 1],
      [0, 1, 1, 1, 1, 1],
      [1, 1, 1, 0, 1, 1],
      [1, 0, 1, 1, 0, 1],
    ],
  },

  f3: {
    id: "AIR309",
    aircraft: "Airbus A321",
    airline: "Vistara",
    from: "Chennai (MAA)",
    to: "Kolkata (CCU)",
    departure: "2026-07-30T20:15:00",
    arrival: "2026-07-30T22:45:00",
    gate: "C5",
    terminal: "1",
    delay: 0,
    status: "SCHEDULED",
    boardingStarted: false,

    layouts: ["A", "B", "C", "D", "E", "F"],

    seats: [
      [1, 1, 1, 1, 1, 1],
      [1, 0, 1, 1, 1, 1],
      [1, 1, 0, 0, 1, 1],
      [1, 1, 1, 1, 0, 1],
      [0, 1, 1, 1, 1, 0],
      [1, 1, 1, 1, 1, 1],
    ],
  },

  f4: {
    id: "AIR412",
    aircraft: "Boeing 787 Dreamliner",
    airline: "Air India",
    from: "Mumbai (BOM)",
    to: "Dubai (DXB)",
    departure: "2026-07-30T21:30:00",
    arrival: "2026-07-30T23:55:00",
    gate: "D8",
    terminal: "2",
    delay: 25,
    status: "DELAYED",
    boardingStarted: false,

    layouts: ["A", "B", "C", "D", "E", "F"],

    seats: [
      [1, 0, 1, 1, 1, 0],
      [1, 1, 1, 1, 0, 1],
      [0, 1, 1, 0, 1, 1],
      [1, 1, 0, 1, 1, 1],
      [1, 0, 1, 1, 1, 1],
      [1, 1, 1, 0, 1, 0],
    ],
  },

  f5: {
    id: "AIR518",
    aircraft: "Airbus A320neo",
    airline: "Akasa Air",
    from: "Pune (PNQ)",
    to: "Goa (GOI)",
    departure: "2026-07-30T16:10:00",
    arrival: "2026-07-30T17:15:00",
    gate: "A1",
    terminal: "1",
    delay: 0,
    status: "DEPARTED",
    boardingStarted: false,

    layouts: ["A", "B", "C", "D", "E", "F"],

    seats: [
      [1, 1, 1, 1, 1, 1],
      [1, 1, 0, 1, 1, 1],
      [1, 0, 1, 1, 0, 1],
      [1, 1, 1, 0, 1, 1],
      [0, 1, 1, 1, 1, 1],
    ],
  },
};
export const passengers = [
  {
    id: 22,
    name: "Christopher Nolan",
    flight: "AIR205",
    seat: "1A",
    row: 0,
    col: 0,
    boarded: false,
  },
  {
    id: 1,
    name: "Aryan Dwivedi",
    flight: "AIR101",
    seat: "1A",
    row: 0,
    col: 0,
    boarded: false,
  },
  {
    id: 2,
    name: "Stanley Kubrick",
    flight: "AIR101",
    seat: "1B",
    row: 0,
    col: 1,
    boarded: false,
  },
  {
    id: 3,
    name: "David Lynch",
    flight: "AIR101",
    seat: "1D",
    row: 0,
    col: 3,
    boarded: false,
  },
  {
    id: 4,
    name: "Ingmar Bergman",
    flight: "AIR101",
    seat: "1F",
    row: 0,
    col: 5,
    boarded: false,
  },

  {
    id: 5,
    name: "Akira Kurosawa",
    flight: "AIR101",
    seat: "2B",
    row: 1,
    col: 1,
    boarded: false,
  },
  {
    id: 6,
    name: "Satyajit Ray",
    flight: "AIR101",
    seat: "2C",
    row: 1,
    col: 2,
    boarded: false,
  },
  {
    id: 7,
    name: "David Fincher",
    flight: "AIR101",
    seat: "2D",
    row: 1,
    col: 3,
    boarded: false,
  },
  {
    id: 8,
    name: "Robert Altman",
    flight: "AIR101",
    seat: "2E",
    row: 1,
    col: 4,
    boarded: false,
  },
  {
    id: 9,
    name: "Wong Kar Wai",
    flight: "AIR101",
    seat: "2F",
    row: 1,
    col: 5,
    boarded: false,
  },

  {
    id: 10,
    name: "Quentin Tarantino",
    flight: "AIR101",
    seat: "3A",
    row: 2,
    col: 0,

    boarded: false,
  },
  {
    id: 11,
    name: "Paul T Anderson",
    flight: "AIR101",
    seat: "3E",
    row: 2,
    col: 4,

    boarded: false,
  },
  {
    id: 12,
    name: "Steven Spielberg",
    flight: "AIR101",
    seat: "3F",
    row: 2,
    col: 5,

    boarded: false,
  },

  {
    id: 13,
    name: "Sidney Lumet",
    flight: "AIR101",
    seat: "4A",
    row: 3,
    col: 0,

    boarded: false,
  },
  {
    id: 14,
    name: "Hayao Miyazaki",
    flight: "AIR101",
    seat: "4B",
    row: 3,
    col: 1,

    boarded: false,
  },
  {
    id: 15,
    name: "Martin Scorsese",
    flight: "AIR101",
    seat: "4C",
    row: 3,
    col: 2,

    boarded: false,
  },
  {
    id: 16,
    name: "Andrei Tarkovsky",
    flight: "AIR101",
    seat: "4D",
    row: 3,
    col: 3,

    boarded: false,
  },
  {
    id: 17,
    name: "Alfred Hitchcock",
    flight: "AIR101",
    seat: "4E",
    row: 3,
    col: 4,

    boarded: false,
  },
  {
    id: 18,
    name: "Rob Reiner",
    flight: "AIR101",
    seat: "4F",
    row: 3,
    col: 5,

    boarded: false,
  },

  {
    id: 19,
    name: "Francis F Coppola",
    flight: "AIR101",
    seat: "5C",
    row: 4,
    col: 2,

    boarded: false,
  },
  {
    id: 20,
    name: "George Lucas",
    flight: "AIR101",
    seat: "5D",
    row: 4,
    col: 3,

    boarded: false,
  },
  {
    id: 21,
    name: "Robert Zemeckis",
    flight: "AIR101",
    seat: "5F",
    row: 4,
    col: 5,

    boarded: false,
  },
];
